const actions = {
	ADD_NOTIFICATION: "ADD_NOTIFICATION",
	REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
	UPDATE_SERVICE_REQUESTS: "UPDATE_SERVICE_REQUESTS",
	ASSIGN_SERVICE_REQUEST: "ASSIGN_SERVICE_REQUEST",
	UPDATE_ROOMS: "UPDATE_ROOMS"
}

module.exports = actions;