const actions = {
	ADD_NOTIFICATION: "ADD_NOTIFICATION",
	REMOVE_NOTIFICATION: "REMOVE_NOTIFICATION",
	UPDATE_SERVICE_REQUESTS: "UPDATE_SERVICE_REQUESTS",
	UPDATE_ROOMS: "UPDATE_ROOMS",
	UPDATE_CUSTOMERS: "UPDATE_CUSTOMERS"
}

module.exports = actions;